### ISSUE TITLE
Large dose dosen't work. Error: could not solve ODE, IDID=-1

### ISSUE THREAD

**Issue by Sibojang9** [hallowkm/RxODE#11]
It works with dose equal =1000, but doesn't work with dose equal=10000.  Sounds weird.
**Error:**
![snap3](https://cloud.githubusercontent.com/assets/11802171/26472030/56d2ba34-4172-11e7-905a-028058dc86bf.jpg)

`
library(RxODE)
ode <- "
   C2 = A2/V2 ;
     C5=A5/V5  ;
   d/dt(A1) = - Kabs\*A1  ; 
   d/dt(A2) = Kabs\*A1- K23\*A2 - K32\*A3  - K24\*A2 + K42\*A4   -K20\*A2  ; 
   d/dt(A3)  =         K23\*A2 - K32\*A3;
   d/dt(A4)  =                           K24\*A2 - K42\*A4 ;
   d/dt(A5)  =  (VMAX/(KM+C2))\*C2- KOUT\*A5   ;  "

 mod1 <- RxODE(model = ode, modName = "mod1")  
theta <- c(    
   Kabs= 3, CL  = 12.4, V2 =20, V3 =26,  V4 = 21.6,Q =10,Q2 =0  ,   
    K20 =0.62,  K23 = 0.95,  K32 =0.73,  K24 = 0,  K42 = 0, 
  VMAX=0.624,  KM=7.4,  V5=16, KOUT =0.394 
) 

ev <- eventTable()
ev$add.dosing(dose = 10000 ,nbr.doses=1,dosing.to=1)
ev$add.sampling(0:20)
x <- mod1$run(theta, ev)   
`

**Comment by wwang-at-github** [comment]
you have a bug in your ODEs. should be:
d/dt(A2) = Kabs*A1- K23*A2 + K32*A3 - K24*A2 + K42*A4 -K20*A2 ;

**Comment by Sibojang9** [comment]
Thank you so much for your input. It was fixed once I changed the code.
