### ISSUE TITLE
Issue in compile model

### ISSUE THREAD

**Issue by JeanUTHSC** [hallowkm/RxODE#9]
Following the tutorial to compile the model in the example, but always run into error/warning message in R3.3 or RStudio :

> mod1 <- RxODE(model = ode, modName = "mod1", wd = work)
Warning message:
running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-33~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB="C:/Users/LABMAI~1/DOCUME~1/mod1.d/mod1.dll" WIN=64 TCLBIN=64 OBJECTS="C:/Users/LABMAI~1/DOCUME~1/mod1.d/mod1.o C:/Users/LABMAI~1/DOCUME~1/mod1.d/call_dvode.o"' had status 127 
Error in cmpMgr$compile() : 
  error loading dll file C:/Users/LABMAI~1/DOCUME~1/mod1.d/mod1.dll
In addition: Warning message:
running command 'C:/PROGRA~1/R/R-33~1.3/bin/R CMD SHLIB C:/Users/LABMAI~1/DOCUME~1/mod1.d/mod1.c C:/Users/LABMAI~1/DOCUME~1/mod1.d/call_dvode.o' had status 1

**Comment by wwang-at-github** [comment]
you'll need rtools 3.4 installed & configured.  could you send me your PATH environment variable?

**Comment by JeanUTHSC** [comment]
Thanks and yes I've installed rtools 3.4 and verified by Rcpp but still not helping... And my PATH is:

Sys.getenv('PATH')
[1] "C:\\Program Files (x86)\\AMD APP\\bin\\x86_64;C:\\Program Files (x86)\\AMD APP\\bin\\x86;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;c:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;c:\\Program Files (x86)\\Microsoft SQL Server\\100\\DTS\\Binn\\"

**Comment by wwang-at-github** [comment]
looks like you didn't configure your rtools & r correctly. pls add the following into your path:
c:\rtools\bin;c:\rtools\mingw_64\bin;C:\PROGRA1\R\R-331.3\bin\x64;

send me the new PATH afterwards.

**Comment by JeanUTHSC** [comment]
Thanks! Here it is:
 "c:\\Rtools\\bin;c:\\Rtools\\mingw_32\\bin;C:\\Program Files (x86)\\AMD APP\\bin\\x86_64;C:\\Program Files (x86)\\AMD APP\\bin\\x86;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;c:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;c:\\Program Files (x86)\\Microsoft SQL Server\\100\\DTS\\Binn\\;c:\\rtools\\mingw_64\\bin;C:\\PROGRA1\\R\\R-331.3\\bin\\x64;"

**Comment by JeanUTHSC** [comment]
I tried the mod1 code. Issue solved! Wonderful, thanks a million!
